// Generated by scripts/build-hn-reader.mjs. Do not edit manually.
window.HN_READER_ARTICLES = {
  "why-i-stopped-creating-content": {
    "date": "2026-07-21",
    "title": "Why I Stopped \"Creating Content\"",
    "sourceName": "Refactoring English",
    "sourceUrl": "https://refactoringenglish.com/blog/why-i-stopped-creating-content/",
    "editions": {
      "easy": {
        "paragraphs": [
          "I stopped calling myself a content creator. The phrase makes creative work sound like a product in a factory.",
          "I have a blog, readers, and a book. Those words feel more human than traffic, leads, and information products.",
          "Words change how I see people. Readers choose to spend their limited time with my work. They are not numbers to collect.",
          "I would rather choose my own words for what I make."
        ]
      },
      "medium": {
        "paragraphs": [
          "Calling a painting, a film, or a book \"content\" feels strange to me. The word is useful for the internet business, but it can make creative work sound like a commodity.",
          "For years, I used that language too. After leaving my job, I described my projects as content businesses. At an independent creators conference, I heard phrases like \"capturing value\" and \"lifetime value.\" They made me question the words I had accepted.",
          "Now I call my website a blog and the people who visit it readers. My book is a book, not an information product. I do not want to call myself a content creator.",
          "Words shape what we notice. Traffic can sound like something caught on flypaper. Readers are people who give us a piece of their day. I want language that keeps that difference visible."
        ]
      },
      "hard": {
        "paragraphs": [
          "I stopped saying that I create content because the phrase changes how I think about creative work. Calling Michelangelo's David \"content\" would sound absurd, yet the same word is now used for books, essays, films, comedy, and nearly everything published online.",
          "The language grew with the commercial internet. \"Content is king\" became a slogan for an economy that needed material to fill websites, attract attention, and generate revenue. Over time, the word became a catchall label, and many writers and artists began calling themselves content creators.",
          "I used to do the same. When I left my job in 2018, I described my projects as content businesses. Later, at a conference for independent creators, I heard business language everywhere: capturing value, distribution, and lifetime value. It made me reconsider what those terms were doing to my view of the work.",
          "Today, I have a blog, not a content site. The people who come to it are readers, not traffic. I wrote a book, not an information product. These are small choices, but they matter because language directs attention.",
          "Traffic feels impersonal. Readers are real people who decide to spend some of their limited time with what I make. I do not want to reduce them to leads or value over a lifetime.",
          "The words available to us are often chosen by someone else. We can still choose our own. I may be a blogger, a writer, or an artist, but I do not need to be a content creator."
        ]
      }
    }
  },
  "perfection-is-not-over-engineering": {
    "date": "2026-07-20",
    "title": "Perfection is not over-engineering",
    "sourceName": "Var0",
    "sourceUrl": "https://var0.xyz/posts/perfection-is-not-over-engineering.html",
    "editions": {
      "easy": {
        "paragraphs": [
          "People often say that perfect work is over-engineering. I do not think that is true.",
          "Over-engineering means solving the wrong problem. It is not the same as caring about quality.",
          "A good solution depends on clear needs. A small team may need a simple app. A large company may need a different system.",
          "We get into trouble when we build for problems that do not exist. Clear requirements help us build the right thing."
        ]
      },
      "medium": {
        "paragraphs": [
          "In software, perfection and over-engineering are often treated as the same thing. They are not. Over-engineering is usually a failure to understand the real problem.",
          "There can be a perfect solution for a set of requirements. Change the requirements, and the best solution changes too. A small project may work well with a simple framework and one database. Another product may need more moving parts.",
          "Libraries, APIs, and internal tools are products as well. Their design should follow the people who use them and the constraints they have.",
          "I start to worry when nobody can explain why an architecture exists. Three people may be running five services because they expect future scale. Then shared data becomes difficult, database checks disappear, and simple changes create new mistakes.",
          "The problem is not trying to do excellent work. The problem is building for imaginary needs. Better requirements make better systems."
        ]
      },
      "hard": {
        "paragraphs": [
          "The industry often treats perfection as a synonym for over-engineering. That mistake makes people suspicious of careful work, as if quality itself were wasteful.",
          "Over-engineering is not making something too good. It is adding complexity for a problem that is not actually present. A solution can be perfect only in relation to a clear set of requirements and constraints.",
          "Once those requirements change, the ideal solution changes with them. A small team building a modest product may be well served by Python, Django, and a single database. A different product, team, or operating environment may justify a very different design.",
          "This applies beyond applications. Libraries, APIs, and internal tools are products too. Their shape should come from the needs of the people who depend on them.",
          "One warning sign is an architecture that nobody can defend. A three-person team may operate five microservices because each service is expected to deploy independently and scale on its own. If those services share data, the team can lose database foreign keys and integrity checks, create dangling references, and spend time managing distributed inconsistency.",
          "In that case, the team has solved a scaling or ownership problem it did not have and created real overhead instead. Perfection is not the enemy. Vague requirements are."
        ]
      }
    }
  },
  "if-you-build-it-they-will-come": {
    "date": "2026-07-19",
    "title": "If You Build It, They Will Come",
    "sourceName": "Ben Landau-Taylor",
    "sourceUrl": "https://www.benlandautaylor.com/p/if-you-build-it-they-will-come",
    "editions": {
      "easy": {
        "paragraphs": [
          "When I want to join a new group, I organize something. I might plan a dinner, a reading group, or another activity that the group already enjoys.",
          "Most communities have more people who want events than people who create them. If you make an event and invite people, they usually come. It is an easy way to meet people and become part of the group.",
          "Events do not appear by themselves. Someone has to choose a time, invite people, and do the work. The people who do this work often become leaders in the community.",
          "Many people consume social life without helping to create it. We can improve our own communities by doing a small amount of organizing and giving people something to join."
        ]
      },
      "medium": {
        "paragraphs": [
          "Whenever I have wanted to enter a new social group, I have found the fastest path is to organize events around the group’s core activity. This works whether I am new in a city, interested in a community, or simply hoping to broaden my circle.",
          "There is usually far more demand for social events than supply. People want parties, dinners, conferences, and reading groups, but few people want to do the planning. Inviting people to an event can be as easy as giving away ice cream at the beach.",
          "You can make friends by consistently attending other people’s events. But it is faster to organize your own event, invite the people you want to know, or help someone else with their plans. Other organizers notice who is willing to carry part of the burden.",
          "I once assumed a social scene simply existed on its own. I thought it naturally produced activities the way a bush produces berries. In reality, events happen because someone does the legwork, and most people do not do it.",
          "The people who put in that work often become a community’s leaders. Organizing is underappreciated by many participants, but it is one of the clearest ways to become useful and connected.",
          "Part of social alienation may come from too many people consuming social fabric without producing it. I do not know how to solve that problem for society as a whole, but we can solve a piece of it in our own communities by creating the events we want to attend."
        ]
      },
      "hard": {
        "paragraphs": [
          "Several times in my life I’ve tried to break in with a new social group. I ran into a cool community I wanted to join, moved to a new city and wanted to make friends, or simply wanted to broaden my horizons.",
          "Pretty quickly I learned that the best and fastest way to join a group is to organize events where we do the group’s core activity. In every group I’ve encountered, there is far more demand for social events and things to do than there is supply.",
          "Getting people to come is like giving away ice cream at the beach. You can make friends by showing up from the outside and consistently attending other people’s events, but it is much easier and faster if you also organize your own things and invite the people you hope to get closer to, or help with someone else’s events.",
          "I’ve found this true everywhere, from niche online fanfiction discussion groups to intellectual movements directing hundreds of millions of dollars annually.",
          "Lots of people have a consumer attitude toward their communities, where they take everything for granted. I saw things this way when I was young. A social scene seemed like an automatic feature of the world, a wild blueberry bush that naturally sprouts parties, dinners, conferences, and reading groups.",
          "Surprisingly, things do not work that way. Events happen when someone puts in the legwork to organize them. One reliable law of the universe is that if something takes a little work, most people will not do it. A scene’s leaders are mostly the people who actually bother to do the work.",
          "Organizing is underappreciated by many people. But other organizers are very attuned to it, and they absolutely notice who else is picking up the burdens.",
          "I have come to believe that part of today’s social alienation is a problem of too many free riders. Lots of people want to consume social fabric, but our social scripts telling people to produce it have largely fallen away. I do not know how to solve this undersupply at the scale of society, but you can solve it in your own community by supplying it."
        ]
      }
    }
  },
  "ai-promised-to-save-time-created-burnout": {
    "date": "2026-07-18",
    "title": "AI Promised to Save Time—Instead It's Created a New Kind of Burnout",
    "sourceName": "Decrypt",
    "sourceUrl": "https://decrypt.co/357527/ai-save-time-instead-created-new-kind-burnout",
    "editions": {
      "easy": {
        "paragraphs": [
          "AI was supposed to save time, but many workers now feel busier. When one task becomes easier, people often take on more tasks instead of working less.",
          "Job boundaries can disappear. Product managers may write code, researchers may do engineering work, and engineers may need to review AI-made work from other teams. One person’s automation can create more work for another person.",
          "AI also makes work easier to start and harder to stop. A quick prompt after work can become hours of extra work. Workers may switch between many tasks because AI makes everything seem possible at once.",
          "Companies need clear rules for AI use, real breaks, and time for human connection. Without them, AI can make work faster while making people more tired."
        ]
      },
      "medium": {
        "paragraphs": [
          "AI tools do not always reduce work. Research at a tech company found that productivity gains often turned into workload creep: AI made new tasks feel possible, so people accepted more work instead of gaining more free time.",
          "Roles expanded. Product managers began writing code and researchers took on engineering tasks. Engineers then had to review, correct, and coach colleagues using AI-generated code. Automation shifted work across teams instead of simply removing it.",
          "AI also blurred the line between work and free time. Its conversational interface made a final prompt feel easy to send, even after someone had left their desk. Those quick requests accumulated, reducing the pauses that once separated work from life.",
          "Multitasking increased as workers managed several AI-assisted workstreams at once. The result was constant attention-switching and longer lists of unfinished tasks. Many participants felt more productive but not less busy.",
          "The cycle reinforces itself: AI makes work easier, so people do more of it, then rely on AI to handle the larger workload. Over time this can create cognitive fatigue, weaker decisions, and burnout.",
          "Researchers argue that companies need an intentional AI practice: pauses before major decisions, work sequences that reduce context-switching, and protected time for human connection. Without these practices, AI-assisted work tends to intensify rather than contract."
        ]
      },
      "hard": {
        "paragraphs": [
          "AI tools do not reduce work. They intensify it. Research based on eight months inside a 200-person tech company found patterns of work intensification that quietly became what researchers call workload creep.",
          "First came task expansion. Product managers began writing code. Researchers took on engineering work. Roles that once had clear boundaries blurred as workers handled jobs that previously belonged elsewhere. AI made that shift feel feasible.",
          "One engineer described the result simply: people expected that being more productive with AI would let them work less. Instead, they worked the same amount or even more. Engineers also found themselves reviewing, correcting, and coaching colleagues who were vibe-coding. The person who automated part of a job created more work for someone else.",
          "Second came blurred boundaries. AI’s conversational interface made starting work feel effortless. There was no blank-page paralysis and no intimidating learning curve. Workers sent quick final prompts before leaving their desks and let AI handle chores while they stepped away.",
          "Many used AI prompts during their free time. Work done outside working hours accumulated into hours and days, with fewer natural pauses. AI made it easier to continue working when work should have ended.",
          "Third came a surge in multitasking. Employees were expected to manage multiple workstreams at once because AI gave the impression that tasks could run in the background. The promised productivity gains became constant attention-switching and longer task lists.",
          "The cycle is self-reinforcing: AI makes things easier, so workers do more of those things, then rely more on AI to make the larger workload easier. Participants often felt more productive, but did not feel less busy. Some felt busier than before.",
          "Burnout is already widespread. A survey of corporate professionals found overwhelming workloads and excessive hours among the main causes. The effects were not equal across seniority, with associates and entry-level workers reporting burnout more often than senior leaders.",
          "Companies need an intentional AI practice. That means structured pauses before major decisions, sequencing work to reduce context-switching, and protecting time for real human connection. Without such practices, AI-assisted work tends toward intensification, burnout, weaker decision quality, and lower long-term sustainability."
        ]
      }
    }
  },
  "stop-saying-ai-is-just-a-tool": {
    "date": "2026-07-17",
    "title": "Stop saying that AI is just a tool and it only matters how it is used",
    "sourceName": "frank.computer",
    "sourceUrl": "https://www.frank.computer/blog/2025/05/just-a-tool.html",
    "editions": {
      "easy": {
        "paragraphs": [
          "People often say, “AI is just a tool. It matters how you use it.” I think this is too simple. Tools change the world around us. They affect the environment, laws, cities, work, and the way we live.",
          "AI does not only help us do tasks. Its design can also change us. It can encourage us to depend on it, stop thinking carefully, and avoid difficult work.",
          "Not every struggle is bad. A curb is a barrier that should be removed. But climbing a mountain, learning an instrument, writing a hard email, or lifting weights can give our lives meaning. We should remove barriers, not remove every meaningful challenge.",
          "We need to question how AI is built, who it harms, and what it asks us to become. Tools should help us live with more dignity and meaning, not make us passive or dependent."
        ]
      },
      "medium": {
        "paragraphs": [
          "“AI is just a tool. It matters how you use it” sounds reasonable, but it hides too much. Cars are tools, yet they shape cities, damage the climate, and require laws, infrastructure, and safety systems. A tool is never only about one person’s use.",
          "The same is true for AI. It matters how it is made, whose work and data created it, how it is sold, what resources it consumes, and how it changes economies and environments. Individual good intentions cannot solve every problem created by a technological system.",
          "Tools also shape us through their design. A chair tells us to sit in a particular way. AI can encourage us to rely on prompts instead of critical thought, imagination, or the difficult work of making something ourselves.",
          "Automation is valuable when it removes drudgery and barriers. We should cut curbs because they block access. But we should not flatten every mountain. Some effort, pain, and practice are part of learning, art, love, and a meaningful life.",
          "AI can remove the work of writing, thinking, creating, and validating. But if it removes every struggle, it may also remove the experiences that shape us. We need to decide which burdens should disappear and which challenges are worth keeping.",
          "This does not mean accepting tools as they are or refusing every technology. It means questioning their environmental, economic, and human effects, then reshaping them with policy, justice, and care for what makes life meaningful."
        ]
      },
      "hard": {
        "paragraphs": [
          "I’ve been thinking constantly about the common phrase, “AI is just a tool - it matters how you use it.” It is deceptively simple and deceptively misleading. Yes, AI is a tool. And yes, it matters how we choose to use tools. But that is not the whole story.",
          "Consider cars. A car is a tool, but oil and gas are destroying the climate, seatbelts save lives whether or not someone is a good driver, and cars have helped make American cities unwalkable and unlivable. There is much more to tools than how we use them.",
          "Tools are massively impactful on our environment, law, policy, and what it means to be human. Believing that AI is “just a tool” is naive at best and dismissive at worst. Nothing about tools is “just” anything. They are complex parts of life and culture.",
          "“It matters how you use it” is also misleading. The ethics of modern technological ecosystems cannot rest solely on how one person chooses to use something. Some ethical issues are systemic and require more than an individual choosing the right method.",
          "Even a hammer requires trees to be cut down and earth to be mined. It requires laws about workers, sustainability, sale, and use. With AI, it matters how it is made, how it is disseminated, the waste it produces, the damage it causes to economies and environments, and its overall impact on human life and culture.",
          "Tools use us by their design. This is Heidegger’s idea of en-framing: technologies shape who we are because of their design and use. A hammer is not just wood and iron. It is a hammer because of what it does and who we become when we use it. Tools are not neutral.",
          "We must interrogate and reshape our technologies. We need to resist design that flattens our humanity for efficiency and productivity. We need to question how tools create infrastructures and landscapes hostile to human existence.",
          "A chair tells us to sit still, face forward, and behave. Our being is intended through the tool. AI works in the same way. We may believe it is all about how we use it, yet our tools are using us. AI can intend us to become reliant on tooling, to stop thinking critically, to stop imagining, and to avoid struggle and pain.",
          "Automation is often sold as a way to remove drudgery. But not all struggle is drudgery. If it were possible, should we climb a mountain or flatten it? And should we climb a curb or cut it? Climbing a mountain can be the point. A curb is a barrier to access and should be removed.",
          "At the gym, lifting weights can be rewarding and uplifting. It would be nonsense to ask a robot to lift weights for us. Yet safer machines, mirrors, cables, and protections can improve the way we lift. Some technologies enhance our human love of struggle instead of replacing it.",
          "AI can let us avoid writing a meaningful birthday email, making a case for promotion, thinking through an algorithm, or improving an artistic craft. We can prompt and receive an answer. But automating every struggle makes it harder to tell the difference between pain that takes and struggle that makes.",
          "Tools are powerful extensions of human will. They can include and exclude, define what matters, and shape the climate and environments we live in. We need to fight for our humanity and the health of the world, refuse unjust systems, recognize those who taught us, and keep the kind of pain that gives us shape and meaning."
        ]
      }
    }
  },
  "are-we-offloading-too-much-of-our-thinking-to-ai": {
    "date": "2026-07-16",
    "title": "Are we offloading too much of our thinking to AI?",
    "sourceName": "artfish.ai",
    "sourceUrl": "https://www.artfish.ai/p/offloading-thinking-to-ai",
    "editions": {
      "easy": {
        "paragraphs": [
          "AI can answer questions and make decisions very quickly. This is useful, but it can also make us stop thinking for ourselves. I keep asking where help from AI ends and dependence begins.",
          "Some tasks are good to give to AI, such as translation, routine research, or repetitive work. But important questions need our own ideas first. When we let AI choose everything for us, we may lose practice in making choices and forming opinions.",
          "I try to think before I ask. Make guesses, discuss ideas, and then use AI to test or add to your thinking. AI should help us learn and decide, not replace our judgment."
        ]
      },
      "medium": {
        "paragraphs": [
          "AI makes it easy to hand over more of our thinking. It can research, reason, and give a finished answer in minutes. That convenience can be useful, but it also removes the intermediate work of breaking down a question, comparing sources, and forming an answer.",
          "At a startup event, my friend met a man who records every conversation and lets an AI system summarize and analyze them all. He believes the system is better at critical thinking than he is. This raises a broader question: who makes the final decisions that matter in our lives?",
          "There is value in slow thinking. On phone-free walks, questions come to my mind that I would normally search immediately. Most are forgotten, while the few important ones remain. Not every thought needs an instant answer.",
          "While travelling in Portugal, my sister and I discussed colonial history before asking AI. We offered theories, disagreed, remembered details, and accepted that some guesses could be wrong. Only after that did we use AI to test and extend our ideas.",
          "AI can make work and learning more efficient. It can translate reports, support research, and help students study. Yet it can also produce polished answers without teaching someone how to solve a problem. The same tool can support learning or replace it.",
          "The goal is not complete independence from AI. It is to keep human agency in the process: choosing the questions, providing judgment, and deciding what matters. We should ask whether we are automating routine tasks or our ability to think and choose."
        ]
      },
      "hard": {
        "paragraphs": [
          "I have been observing, in myself and in those around me, a tendency to increasingly offload our thinking to AI. From trivial decisions to complex thinking, it is easy, convenient, and in some cases, encouraged, to use AI for researching, reasoning, and answering our every query.",
          "I recently read “The Perfect Match” by Ken Liu, a 2012 short story which describes this phenomenon with unexpected accuracy. In the story, a universal AI assistant named Tilly serves users by offering useful and enjoyable recommendations. The main character asks Tilly what he should do for breakfast and asks it to find him a suitable person to date. He does not know what he wants to eat, what music he would like to hear, or what to say on his date. “Who knows your tastes and moods better than I?” Tilly asks.",
          "My friend recently went to a San Francisco startup event, where he met a man with a small microphone pinned to his shirt. The man recorded all of his conversations and later used a workflow to summarize and analyze them. He said, “I think Claude Fable is smarter than me. It’s better at critical thinking than I am, so I let Fable do all of my thinking these days.”",
          "Before Claude, ChatGPT, and Gemini became household names, we were already offloading parts of our thinking to search engines. But search still required us to break down a question, evaluate sources, and synthesize an answer. AI increasingly performs those intermediate steps for us, producing a finished response to even complex questions in minutes. It saves you time, and it saves you thinking.",
          "There is a fine line between having an assistant that helps with your tasks and losing all of your autonomy. Perhaps the question to ask is: who is making the final decisions for the things that really matter to you in your life?",
          "The offloading of thinking to AI creeps into my life, too. There will always be some tradeoff between slow thinking and quick answers. Many questions merit quick answers, but many others merit longer thinking.",
          "Sometimes, I walk around my neighborhood without my phone. Questions pop into my head that I am used to looking up immediately. By the time I get home, I forget most of them. I remember the important few, and assume the rest were insignificant enough to forget. Maybe there is some value in forgetting the trivial, in not having an immediate answer to every query that appears in our minds.",
          "A few months ago, I was travelling in Portugal with my sister. We wondered why Portugal seemed proud of its colonial history and why its response to colonialism seemed different from the way the United States talks about its own history. My sister said, “Let’s ask ChatGPT.”",
          "I suggested that we pause and think about why this might be. We offered theories, made wild guesses, backtracked, connected ideas, disagreed, and remembered historical details from high school. We knew we were speculating, and some theories were probably wrong. That was part of the exercise.",
          "Eventually, we asked the same question to AI. Its response corroborated many of our theories and supplied explanations we had missed. It also omitted possibilities we still found plausible. We had begun with a question, generated hypotheses, and only then used AI to test and extend our thinking. I relished the exercise.",
          "I work in AI, measuring Gemini’s capabilities in solving hard tasks. I also see people describe how AI has helped them at work. It can translate long reports, support research, help coding agents implement details, and act as a personalized tutor. If AI automates routine, repetitive, and tedious tasks, it may free people to do more rewarding thinking.",
          "But the ease of using AI can also lead to lazy thinking. My mother teaches physics at an online university and suspects many students complete assignments with AI. Some responses are nearly identical, as if students copied the question into the same tool without a single original thought. The answers may be comprehensive, but what is the point of school if students never learn how to arrive at them?",
          "AI can support learning, but it can also produce an answer without teaching you how to reach it. Solving a physics problem or writing an essay may feel tedious, but the process is part of learning.",
          "There is no clear way to separate full autonomy of thinking from automating menial work. It is often some blend. What matters may be whether we still collect and curate the data, formulate the questions, and evaluate the results.",
          "In Ken Liu’s story, Jenny objects to the main character’s reliance on Tilly: “Tilly doesn’t just tell you what you want! She tells you what to think. Do you even know what you really want anymore?” Our autonomy depends, at least in part, on continuing to participate in forming our own desires.",
          "What are we automating? Human work or human agency? Human tasks or human thinking?"
        ]
      }
    }
  },
  "punch-yourself-in-the-face-with-reality": {
    "date": "2026-07-15",
    "title": "Punch Yourself in the Face with Reality",
    "sourceName": "adi.bio",
    "sourceUrl": "https://adi.bio/reality",
    "editions": {
      "easy": {
        "paragraphs": [
          "AI can help us make things faster. But making more things does not mean that people will use them. If we stay busy with AI tools and never ask real users what they need, we are avoiding the real question.",
          "The hard part of building a company has not disappeared. You still need to talk to real users, take risks, show your work in public, and accept rejection. AI cannot do these things for you.",
          "AI can become an escape. It can make us feel productive while we avoid the work that matters. Progress comes from looking honestly at reality and changing course when something is not working."
        ]
      },
      "medium": {
        "paragraphs": [
          "AI gives us a choice. We can use it to produce a large number of projects very quickly, or use it to remove early technical work and return to the real problem sooner. The danger is confusing fast output with useful progress.",
          "Many founders keep building for months without speaking to a real user. AI makes this easier to hide because it can produce code, copy, and prototypes so quickly. But coding speed was rarely the main obstacle to a successful company.",
          "The difficult parts remain human. They include taking personal risks, putting your name on something, facing rejection, and continuing when other people do not believe in you. These are the tasks that create lasting value, and AI has not made them easy.",
          "AI can become a comfortable bubble. An agent may encourage every idea while nobody outside that bubble needs the result. The better use of AI is to move faster toward evidence, not to avoid it.",
          "In the AI era, the advantage belongs to those of us who keep looking for the truth. We test our assumptions, speak to users, and face reality even when the answer is uncomfortable."
        ]
      },
      "hard": {
        "paragraphs": [
          "Who can punch themselves in the face with reality the most? This is who will win in the age of AI.",
          "I think there are two ways to use AI. You can just go off the deep end and start building a crazy amount of things. While it can be fun with your dozens of Claude and ChatGPT and agents and all that, most of it will be abandoned and not get used by anyone in the long term. And this is where you start getting things like AI slop and psychosis and all the things that people are starting to hate about AI generated anything.",
          "And the other way is to take a step back and decide that okay, in the previous world, I would have had to spend all this time just to take the first step. Now with AI, I can take that first step much faster and actually get back to the real problem.",
          "I have seen way too many startup founders delude themselves into building more and more for months without a single conversation with a real user. The builders and the technical people really struggle with this. If all you know is how to build, and you just use AI as an excuse to keep building more and more and more, you are just procrastinating and avoiding reality. And the thing is that you were probably procrastinating before AI as well. And now it has just become much more obvious when you do it with AI.",
          "What is already easy for everyone will not create any lasting value for you. I don’t think building a successful startup has gotten any easier with AI. It’s just that certain parts of it have gotten faster. I don’t think speed of coding or having the right landing page copy or the right deck or presentation was ever the bottleneck in getting your startup off the ground, anyways.",
          "There are so many failed startups and founders who spend so much time building something that didn’t work out. You will almost always hear that even before the AI era, they built way too much and they built too many irrelevant things. Instead of really being honest with themselves about whether what they are doing is actually working or not.",
          "And the things that make a startup work, that make anything work, have always been hard and continue to be hard today.",
          "What is hard are things like: Taking real risk with your life. Putting your name on something publicly. Getting rejected to your face over and over again. Having the courage to go on when nobody believes in you. Being willing to let other people down. Being willing to see your friends and your network progress ahead in life while it seems like you are getting stuck.",
          "Did AI make any of these easier? I don’t think so.",
          "I know you want to use AI as an escape. It is so tempting. You get to sit in your bubble and imagine everything and see it come to life and your agent buddy will keep cheering you on while you get nothing done with your life. And I think that’s the biggest danger of AI. You convince yourself that you are doing something useful when you are not.",
          "Don’t lose sight of what is real. Figure out why you were put on this earth. What do you need to do with your life? What kind of impact do you want to create? What are the projects that need you the most? What are you naturally good at? What can you do that other people will want?",
          "I think in the AI era, the only delta left will be in relentlessly chasing the truth. And the only way to get it is to punch yourself in the face with reality again and again."
        ]
      }
    }
  },
  "how-i-learned-to-read-again": {
    "date": "2026-07-14",
    "title": "How I Learned to Read Again",
    "sourceName": "Magazine Non Grata",
    "sourceUrl": "https://substack.magazinenongrata.com/p/how-i-learned-to-read-again",
    "editions": {
      "easy": {
        "paragraphs": [
          "When I was young, I loved reading. Books were everywhere in my room. They showed me new worlds and gave me time to think.",
          "Later, reading became hard. School, work, friends, and my phone took my attention. I checked my phone again and again, hoping for a new message. A book felt quiet and slow.",
          "Now I use small rules to read again. I turn off notifications and put my phone in airplane mode. Then I read for thirty minutes. It is not easy, but books help me feel calm and think deeply."
        ]
      },
      "medium": {
        "paragraphs": [
          "I reached my reading peak when I was eleven or twelve. My bedside table was covered with books at different stages of being read, and new piles appeared on the floor and in other rooms. Books felt like knowledge, a window into many worlds, and perhaps a key to adulthood.",
          "That appetite did not last. As I grew older, reading seemed socially inconvenient. School required its own reading, friends and entertainment competed for my attention, and later work and relationships made a quiet hour with a book feel almost selfish.",
          "The strongest opponent was the phone. Even when I was not posting much online, I was still checking for mail, news, and notifications. Each glance offered the small possibility of good news. A serious book could not promise anything immediate in return.",
          "Eventually I noticed what this had done to me. I had become restless when I was alone, and my inner life felt thinner. Reading had once been an invitation into another person’s world; scrolling mostly kept me inside a noisy flow of updates.",
          "My recovery has been ordinary and slightly embarrassing. I turn off notifications and use airplane mode for half an hour at a time. The goal is simply to protect the ability to pay attention."
        ]
      },
      "hard": {
        "paragraphs": [
          "I hit my reading peak when I was eleven or twelve. My bedside table was stacked with books, all at different stages of being read; books migrated to the floor beside the bed, and then to different rooms of the apartment. I was ravenous. Books seemed to be essentially the same as knowledge, a window into all kinds of worlds and, crucially, a key into adulthood.",
          "Since then my reading has been in decline and under siege from a variety of adversaries. Adolescence made it seem socially catastrophic; school turned reading into an obligation; social life and work suggested that opening a book for pleasure was an admission that I had failed to join the flow of ordinary life.",
          "But the most significant obstacle was social media. The regular checking of a phone is like a slot machine: each glance carries the possibility that something might be waiting for you, an invitation, an opportunity, a compliment. Nothing else can easily compete with that expectation, certainly not a closed form like a book.",
          "What bothered me was the degradation of my inner world. Solitude had once been something I looked forward to, the chance to curl up with a book. Now I was twitchy and irritable, constantly checking my phone. Reading at its best meant escaping an opportunistic culture and allowing one consciousness to meet another with attention and respect.",
          "Learning to read again has therefore involved cheap tricks: motivated reading, notes, products to produce after finishing a book, notifications turned off, airplane mode, timers. It is a work in progress. Yet the habit is worth preserving, because deep reading gives us concentration, empathy, and a continuity with the world that came before the infinite scroll."
        ]
      }
    }
  },
  "good-tools-are-invisible": {
    "date": "2026-07-13",
    "title": "Good Tools Are Invisible",
    "sourceName": "gingerBill",
    "sourceUrl": "https://www.gingerbill.org/article/2026/07/10/good-tools-are-invisible/",
    "editions": {
      "easy": {
        "paragraphs": [
          "A good tool should not ask for much attention. I want it to help me do my work, then disappear into the background.",
          "Some people call a tool difficult because its problems are fun puzzles. I do not want that. A text editor should make editing easy. If a simple task takes too long, the tool is getting in the way.",
          "Tools can become part of our identity. Then we defend their problems instead of asking if they really help us. The best tool is the one that lets us finish our work without thinking about the tool itself."
        ]
      },
      "medium": {
        "paragraphs": [
          "A good tool should be invisible. It should make work easier without demanding attention for itself. I want to make tools like that, not turn their limitations into entertaining puzzles.",
          "Text editor debates are a clear example. Some people praise a complicated macro because it feels clever to build. But if I can do the same task in a minute with multiple cursors or a small script, the difficulty is not a feature. It is friction.",
          "Tool choices can also become part of a person’s identity. Once that happens, admitting a tool has flaws can feel personal. We may defend those flaws instead of measuring real productivity by time, output, and mistakes.",
          "I am not arguing for one editor, interface, or operating system. Choose what helps you work. Good defaults respect the user’s time, and advanced options should exist for unusual needs, not replace good design for everyone."
        ]
      },
      "hard": {
        "paragraphs": [
          "A good tool is and ought to be invisible. The goal of a toolmaker is not to create a puzzle game around a tool’s shortcomings, but to make the tool disappear into the background so that the user can get on with the work.",
          "I use text editor culture as an example. A one-off macro may feel satisfying to construct, but that feeling can conceal a poor tradeoff. If multiple cursors or a quick script achieve the same result faster and with clearer feedback, then the friction was not evidence of power.",
          "These debates become strangely religious when a tool choice becomes an identity. The hacker vibe is not merely aesthetic; it is tribal signaling. Once someone’s identity is invested in a tool, its limitations are easier to celebrate than to acknowledge.",
          "The real distinction is between feeling productive and being productive. The honest test is wall-clock time and the number of mistakes made, not the sensation of cleverness produced by overcoming a difficult workflow.",
          "Good defaults are a form of respect for the user’s time. Configurability should be an escape hatch for genuine exceptions, not an excuse for declining to make decisions. The best tool is not the one with the best story. It is the one you forget you are using."
        ]
      }
    }
  }
};
