// Generated by scripts/build-hn-reader.mjs. Do not edit manually.
window.HN_READER_ARTICLES = {
  "are-we-offloading-too-much-of-our-thinking-to-ai": {
    "date": "2026-07-16",
    "title": "Are we offloading too much of our thinking to AI?",
    "sourceName": "artfish.ai",
    "sourceUrl": "https://www.artfish.ai/p/offloading-thinking-to-ai",
    "editions": {
      "easy": {
        "paragraphs": [
          "AI can answer questions and make decisions very quickly. This is useful, but it can also make us stop thinking for ourselves. The writer asks where help from AI ends and dependence begins.",
          "Some tasks are good to give to AI, such as translation, routine research, or repetitive work. But important questions need our own ideas first. When we let AI choose everything for us, we may lose practice in making choices and forming opinions.",
          "The writer suggests a simple habit: think before you ask. Make guesses, discuss ideas, and then use AI to test or add to your thinking. AI should help us learn and decide, not replace our judgment."
        ]
      },
      "medium": {
        "paragraphs": [
          "AI makes it easy to hand over more of our thinking. It can research, reason, and give a finished answer in minutes. That convenience can be useful, but it also removes the intermediate work of breaking down a question, comparing sources, and forming an answer.",
          "The writer describes a person who records every conversation and lets an AI system summarize and analyze them all. He believes the system is better at critical thinking than he is. This is an extreme example, but it raises a broader question: who makes the final decisions that matter in our lives?",
          "There is value in slow thinking. On a phone-free walk, the writer notices questions that would normally be searched immediately. Most are forgotten, while the few important ones remain. Not every thought needs an instant answer.",
          "While travelling, the writer and her sister discussed a question about Portuguese colonial history before asking AI. They offered theories, disagreed, remembered details, and accepted that some guesses could be wrong. Only after that did they use AI to test and extend their ideas.",
          "AI can make work and learning more efficient. It can translate reports, support research, and help students study. Yet it can also produce polished answers without teaching someone how to solve a problem. The same tool can support learning or replace it.",
          "The goal is not complete independence from AI. It is to keep human agency in the process: choosing the questions, providing judgment, and deciding what matters. We should ask whether we are automating routine tasks or automating our ability to think and choose."
        ]
      },
      "hard": {
        "paragraphs": [
          "I have been observing, in myself and in those around me, a tendency to increasingly offload our thinking to AI. From trivial decisions to complex thinking, it is easy, convenient, and in some cases, encouraged, to use AI for researching, reasoning, and answering our every query.",
          "I recently read “The Perfect Match” by Ken Liu, a 2012 short story which describes this phenomenon with unexpected accuracy. In the story, a universal AI assistant named Tilly serves users by offering useful and enjoyable recommendations. The main character asks Tilly what he should do for breakfast and asks it to find him a suitable person to date. He does not know what he wants to eat, what music he would like to hear, or what to say on his date. “Who knows your tastes and moods better than I?” Tilly asks.",
          "My friend recently went to a San Francisco startup event, where he met a man with a small microphone pinned to his shirt. The man recorded all of his conversations and later used a workflow to summarize and analyze them. He said, “I think Claude Fable is smarter than me. It’s better at critical thinking than I am, so I let Fable do all of my thinking these days.”",
          "Before Claude, ChatGPT, and Gemini became household names, we were already offloading parts of our thinking to search engines. But search still required us to break down a question, evaluate sources, and synthesize an answer. AI increasingly performs those intermediate steps for us, producing a finished response to even complex questions in minutes. It saves you time, and it saves you thinking.",
          "There is a fine line between having an assistant that helps with your tasks and losing all of your autonomy. Perhaps the question to ask is: who is making the final decisions for the things that really matter to you in your life?",
          "The offloading of thinking to AI creeps into my life, too. There will always be some tradeoff between slow thinking and quick answers. Many questions merit quick answers, but many others merit longer thinking.",
          "Sometimes, I walk around my neighborhood without my phone. Questions pop into my head that I am used to looking up immediately. By the time I get home, I forget most of them. I remember the important few, and assume the rest were insignificant enough to forget. Maybe there is some value in forgetting the trivial, in not having an immediate answer to every query that appears in our minds.",
          "A few months ago, I was travelling in Portugal with my sister. We wondered why Portugal seemed proud of its colonial history and why its response to colonialism seemed different from the way the United States talks about its own history. My sister said, “Let’s ask ChatGPT.”",
          "I suggested that we pause and think about why this might be. We offered theories, made wild guesses, backtracked, connected ideas, disagreed, and remembered historical details from high school. We knew we were speculating, and some theories were probably wrong. That was part of the exercise.",
          "Eventually, we asked the same question to AI. Its response corroborated many of our theories and supplied explanations we had missed. It also omitted possibilities we still found plausible. We had begun with a question, generated hypotheses, and only then used AI to test and extend our thinking. I relished the exercise.",
          "I work in AI, measuring Gemini’s capabilities in solving hard tasks. I also see people describe how AI has helped them at work. It can translate long reports, support research, help coding agents implement details, and act as a personalized tutor. If AI automates routine, repetitive, and tedious tasks, it may free people to do more rewarding thinking.",
          "But the ease of using AI can also lead to lazy thinking. My mother teaches physics at an online university and suspects many students complete assignments with AI. Some responses are nearly identical, as if students copied the question into the same tool without a single original thought. The answers may be comprehensive, but what is the point of school if students never learn how to arrive at them?",
          "AI can support learning, but it can also produce an answer without teaching you how to reach it. Solving a physics problem or writing an essay may feel tedious, but the process is part of learning.",
          "There is no clear way to separate full autonomy of thinking from automating menial work. It is often some blend. What matters may be whether we still collect and curate the data, formulate the questions, and evaluate the results.",
          "In Ken Liu’s story, Jenny objects to the main character’s reliance on Tilly: “Tilly doesn’t just tell you what you want! She tells you what to think. Do you even know what you really want anymore?” Our autonomy depends, at least in part, on continuing to participate in forming our own desires.",
          "What are we automating? Human work or human agency? Human tasks or human thinking?"
        ]
      }
    }
  },
  "punch-yourself-in-the-face-with-reality": {
    "date": "2026-07-15",
    "title": "Punch Yourself in the Face with Reality",
    "sourceName": "adi.bio",
    "sourceUrl": "https://adi.bio/reality",
    "editions": {
      "easy": {
        "paragraphs": [
          "AI can help people make things faster. But making more things does not mean that people will use them. Many builders stay busy with AI tools and avoid asking a simple question: does anyone really need this?",
          "The hard part of building a company has not disappeared. You still need to talk to real users, take risks, show your work in public, and accept rejection. AI cannot do these things for you.",
          "The writer says that AI can become an escape. It can make you feel productive while you avoid the work that matters. In the end, progress comes from looking honestly at reality and changing course when something is not working."
        ]
      },
      "medium": {
        "paragraphs": [
          "AI gives builders a choice. They can use it to produce a large number of projects very quickly, or they can use it to remove early technical work and return to the real problem sooner. The danger is confusing fast output with useful progress.",
          "Many founders keep building for months without speaking to a real user. AI makes this easier to hide because it can produce code, copy, and prototypes so quickly. But coding speed was rarely the main obstacle to a successful company.",
          "The difficult parts remain human. They include taking personal risks, putting your name on something, facing rejection, and continuing when other people do not believe in you. These are the tasks that create lasting value, and AI has not made them easy.",
          "The writer warns that AI can become a comfortable bubble. An agent may encourage every idea while nobody outside that bubble needs the result. The better use of AI is to move faster toward evidence, not to avoid it.",
          "In the AI era, the advantage belongs to people who keep looking for the truth. They test their assumptions, speak to users, and face reality even when the answer is uncomfortable."
        ]
      },
      "hard": {
        "paragraphs": [
          "Who can punch themselves in the face with reality the most? This is who will win in the age of AI.",
          "I think there are two ways to use AI. You can just go off the deep end and start building a crazy amount of things. While it can be fun with your dozens of Claude and ChatGPT and agents and all that, most of it will be abandoned and not get used by anyone in the long term. And this is where you start getting things like AI slop and psychosis and all the things that people are starting to hate about AI generated anything.",
          "And the other way is to take a step back and decide that okay, in the previous world, I would have had to spend all this time just to take the first step. Now with AI, I can take that first step much faster and actually get back to the real problem.",
          "I have seen way too many startup founders delude themselves into building more and more for months without a single conversation with a real user. The builders and the technical people really struggle with this. If all you know is how to build, and you just use AI as an excuse to keep building more and more and more, you are just procrastinating and avoiding reality. And the thing is that you were probably procrastinating before AI as well. And now it has just become much more obvious when you do it with AI.",
          "What is already easy for everyone will not create any lasting value for you. I don’t think building a successful startup has gotten any easier with AI. It’s just that certain parts of it have gotten faster. I don’t think speed of coding or having the right landing page copy or the right deck or presentation was ever the bottleneck in getting your startup off the ground, anyways.",
          "There are so many failed startups and founders who spend so much time building something that didn’t work out. You will almost always hear that even before the AI era, they built way too much and they built too many irrelevant things. Instead of really being honest with themselves about whether what they are doing is actually working or not.",
          "And the things that make a startup work, that make anything work, have always been hard and continue to be hard today.",
          "What is hard are things like: Taking real risk with your life. Putting your name on something publicly. Getting rejected to your face over and over again. Having the courage to go on when nobody believes in you. Being willing to let other people down. Being willing to see your friends and your network progress ahead in life while it seems like you are getting stuck.",
          "Did AI make any of these easier? I don’t think so.",
          "I know you want to use AI as an escape. It is so tempting. You get to sit in your bubble and imagine everything and see it come to life and your agent buddy will keep cheering you on while you get nothing done with your life. And I think that’s the biggest danger of AI. You convince yourself that you are doing something useful when you are not.",
          "Don’t lose sight of what is real. Figure out why you were put on this earth. What do you need to do with your life? What kind of impact do you want to create? What are the projects that need you the most? What are you naturally good at? What can you do that other people will want?",
          "I think in the AI era, the only delta left will be in relentlessly chasing the truth. And the only way to get it is to punch yourself in the face with reality again and again."
        ]
      }
    }
  },
  "how-i-learned-to-read-again": {
    "date": "2026-07-14",
    "title": "How I Learned to Read Again",
    "sourceName": "Magazine Non Grata",
    "sourceUrl": "https://substack.magazinenongrata.com/p/how-i-learned-to-read-again",
    "editions": {
      "easy": {
        "paragraphs": [
          "When I was young, I loved reading. Books were everywhere in my room. They showed me new worlds and gave me time to think.",
          "Later, reading became hard. School, work, friends, and my phone took my attention. I checked my phone again and again, hoping for a new message. A book felt quiet and slow.",
          "Now I use small rules to read again. I turn off notifications and put my phone in airplane mode. Then I read for thirty minutes. It is not easy, but books help me feel calm and think deeply."
        ]
      },
      "medium": {
        "paragraphs": [
          "I reached my reading peak when I was eleven or twelve. My bedside table was covered with books at different stages of being read, and new piles appeared on the floor and in other rooms. Books felt like knowledge, a window into many worlds, and perhaps a key to adulthood.",
          "That appetite did not last. As I grew older, reading seemed socially inconvenient. School required its own reading, friends and entertainment competed for my attention, and later work and relationships made a quiet hour with a book feel almost selfish.",
          "The strongest opponent was the phone. Even when I was not posting much online, I was still checking for mail, news, and notifications. Each glance offered the small possibility of good news. A serious book could not promise anything immediate in return.",
          "Eventually I noticed what this had done to me. I had become restless when I was alone, and my inner life felt thinner. Reading had once been an invitation into another person’s world; scrolling mostly kept me inside a noisy flow of updates.",
          "My recovery has been ordinary and slightly embarrassing. I turn off notifications and use airplane mode for half an hour at a time. The goal is simply to protect the ability to pay attention."
        ]
      },
      "hard": {
        "paragraphs": [
          "I hit my reading peak when I was eleven or twelve. My bedside table was stacked with books, all at different stages of being read; books migrated to the floor beside the bed, and then to different rooms of the apartment. I was ravenous. Books seemed to be essentially the same as knowledge, a window into all kinds of worlds and, crucially, a key into adulthood.",
          "Since then my reading has been in decline and under siege from a variety of adversaries. Adolescence made it seem socially catastrophic; school turned reading into an obligation; social life and work suggested that opening a book for pleasure was an admission that I had failed to join the flow of ordinary life.",
          "But the most significant obstacle was social media. The regular checking of a phone is like a slot machine: each glance carries the possibility that something might be waiting for you, an invitation, an opportunity, a compliment. Nothing else can easily compete with that expectation, certainly not a closed form like a book.",
          "What bothered me was the degradation of my inner world. Solitude had once been something I looked forward to, the chance to curl up with a book. Now I was twitchy and irritable, constantly checking my phone. Reading at its best meant escaping an opportunistic culture and allowing one consciousness to meet another with attention and respect.",
          "Learning to read again has therefore involved cheap tricks: motivated reading, notes, products to produce after finishing a book, notifications turned off, airplane mode, timers. It is a work in progress. Yet the habit is worth preserving, because deep reading gives us concentration, empathy, and a continuity with the world that came before the infinite scroll."
        ]
      }
    }
  },
  "good-tools-are-invisible": {
    "date": "2026-07-13",
    "title": "Good Tools Are Invisible",
    "sourceName": "gingerBill",
    "sourceUrl": "https://www.gingerbill.org/article/2026/07/10/good-tools-are-invisible/",
    "editions": {
      "easy": {
        "paragraphs": [
          "A good tool should not ask for much attention. It should help you do your work, then disappear into the background.",
          "Some people call a tool difficult because its problems are fun puzzles. The writer disagrees. A text editor should make editing easy. If a simple task takes too long, the tool is getting in the way.",
          "Tools can become part of our identity. Then we may defend their problems instead of asking if they really help us. The best tool is the one that lets you finish your work without thinking about the tool itself."
        ]
      },
      "medium": {
        "paragraphs": [
          "A good tool should be invisible. It should make work easier without demanding attention for itself. The writer argues that toolmakers should aim for this feeling, rather than treating a tool’s limitations as entertaining puzzles.",
          "Text editor debates are a clear example. Some people praise a complicated macro because it feels clever to build. But if the same task takes a minute with multiple cursors or a small script, the difficulty is not a feature. It is friction.",
          "Tool choices can also become part of a person’s identity. Once that happens, admitting a tool has flaws can feel personal. Users may defend those flaws instead of measuring real productivity by time, output, and mistakes.",
          "The writer is not arguing for one editor, interface, or operating system. The point is to choose what helps you work. Good defaults respect the user’s time, and advanced options should exist for unusual needs, not replace good design for everyone."
        ]
      },
      "hard": {
        "paragraphs": [
          "A good tool is and ought to be invisible. The goal of a toolmaker is not to create a puzzle game around a tool’s shortcomings, but to make the tool disappear into the background so that the user can get on with the work.",
          "The author uses text editor culture as an example. A one-off macro may feel satisfying to construct, but that feeling can conceal a poor tradeoff. If multiple cursors or a quick script achieve the same result faster and with clearer feedback, then the friction was not evidence of power.",
          "These debates become strangely religious when a tool choice becomes an identity. The hacker vibe is not merely aesthetic; it is tribal signaling. Once someone’s identity is invested in a tool, its limitations are easier to celebrate than to acknowledge.",
          "The real distinction is between feeling productive and being productive. The honest test is wall-clock time and the number of mistakes made, not the sensation of cleverness produced by overcoming a difficult workflow.",
          "Good defaults are a form of respect for the user’s time. Configurability should be an escape hatch for genuine exceptions, not an excuse for declining to make decisions. The best tool is not the one with the best story. It is the one you forget you are using."
        ]
      }
    }
  }
};
